#!/bin/bash

#load variables from config
source "lanu-config.sh"

# get all available wifi from NetworkManager and pipe them to DMENU
choice=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | "${DMENU[@]}" 'Select Wifi  :')
 
# test selected network and wait to get password
if [[ "$choice" ]] 
then
  # cut first 17 bytes which contains bssid 
  bssid=$(echo "$choice" | cut -b 1-17)
  pass=$(echo "" | "${DMENU[@]}" 'Enter Password  :')

  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"   
  
  sleep 10   
  
  if ping -q -c 2 -W 2 google.com >/dev/null
  then     
    notify-send "Your internet is working :)"   
  else     
    notify-send "Your internet is not working :("   
  fi
else
  echo "Program terminated." && exit 1
fi  
