#!/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

BATTINFO=$(acpi -b)

/usr/bin/notify-send "LOW battery"

if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 02:55:00 ]]; then
  /usr/bin/notify-send "LOW battery" "$BATTINFO"
fi
