#!/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

BATTINFO=$(acpi -b)

if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:30:00 ]]; then
  /usr/bin/notify-send "LOW battery" "$BATTINFO"
fi

# crontab -e for editing jobs
# crontab -r for removing jobs
# crontab -l check scheduled jobs
